"""`awrtifact serve-spec` — generate the workers from the spec.

The worker's data sections (allowlist regex, whole names, upstream bases, the
split manifest) are computed from the spec — never typed into JS. Generation
is deterministic: `--check` regenerates to a temp dir and compares, so a
drift between spec and committed workers fails loudly (the AE004 pattern:
regenerate, don't hand-edit).

One spec drives EVERY worker in `spec.workers` (or the single store worker):
artifact.aitherium.com and weights.aitherium.com serve the same data because
they are generated from the same file.

The banner names the spec by BASENAME, not path: the file is checked into two
working trees (D: and C:) and the diff-gate compares renders, so an embedded
absolute path would flag every cross-tree checkout.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path

from . import spec as spec_mod
from . import worker_template

DEFAULT_COMPAT_DATE = "2026-01-01"


def render(spec: dict, spec_path: Path, worker: dict | None = None) -> tuple[str, str]:
    """Render (index.js, wrangler.toml) for one worker of a validated spec."""
    worker = worker or spec_mod.workers(spec)[0]
    chunked = spec_mod.chunked_map(spec)
    header = (
        "GENERATED by `awrtifact serve-spec` from the awrtifact spec — DO NOT "
        "EDIT BY HAND.\n"
        f"Regenerate (from the spec's directory): awrtifact serve-spec {spec_path.name}"
    )
    js = (
        worker_template.JS_TEMPLATE
        .replace("__GENERATED_HEADER__", header)
        .replace("__UPSTREAMS_JSON__", json.dumps(spec_mod.upstream_bases(spec), indent=2))
        .replace("__PATH_UPSTREAMS_JSON__", json.dumps(spec_mod.path_upstreams(spec), indent=2))
        .replace("__ALLOWED_SRC__", spec.get("allowlist", {}).get("regex", ""))
        .replace("__WHOLE_JSON__", json.dumps(spec_mod.whole_names(spec)))
        .replace("__CHUNKED_JSON__", json.dumps(chunked, indent=2))
        .replace("__R2_BINDING__", worker.get("r2_binding", "WEIGHTS"))
    )

    route = worker.get("route")
    if route:
        route_block = (
            f'routes = [ {{ pattern = "{route}", zone_name = '
            f'"{spec_mod.zone_for(route)}" }} ]'
        )
    else:
        route_block = "# no custom route: workers.dev only"
    toml = (
        worker_template.TOML_TEMPLATE
        .replace("__WORKER_NAME__", worker["name"])
        .replace("__COMPAT_DATE__", spec.get("store", {}).get("compatibility_date",
                                                              DEFAULT_COMPAT_DATE))
        .replace("__ROUTE_BLOCK__", route_block)
        .replace("__R2_BINDING__", worker.get("r2_binding", "WEIGHTS"))
        .replace("__R2_BUCKET__", worker.get("r2_bucket", "aither-artifacts"))
    )
    return js, toml


def worker_dir(spec_path: Path, worker: dict) -> Path:
    """Where a worker's files live.

    dir is relative to the spec's PARENT'S PARENT (the .DEPLOYMENT/workers
    level) so both workers sit side by side while the spec lives inside its
    own worker's dir. This also keeps the generated worker dir from shadowing
    the `awrtifact` package on `python -m` (a directory named awrtifact on
    sys.path wins over the installed package — measured 2026-08-27).
    """
    return (spec_path.parent.parent / worker["dir"]).resolve()


def emit(spec: dict, spec_path: Path, check: bool = False) -> list[Path]:
    """Write every worker's files next to the spec; `--check` diffs instead.

    Worker files land in <spec dir>/<worker.dir>/; returns the worker dirs.
    In check mode, returns them only when the existing files are identical to
    fresh renders; raises ValueError on the first drift (the diff-gate).

    The spec path is RESOLVED first: Path("x.yaml").parent is "." and
    "." .parent is "." again, so the parent.parent climb silently collapses
    when the spec is passed relative (measured 2026-08-27 — workers emitted
    into a nested dir that then shadowed the package on `python -m`).
    """
    spec_path = Path(spec_path).resolve()
    rendered: list[tuple[Path, str, str]] = []
    for worker in spec_mod.workers(spec):
        js, toml = render(spec, spec_path, worker)
        rendered.append((worker_dir(spec_path, worker), js, toml))

    if check:
        with tempfile.TemporaryDirectory() as tmp:
            tmp = Path(tmp)
            for target, js, toml in rendered:
                rel = target.relative_to(spec_path.parent.parent)
                for name, content in (("index.js", js), ("wrangler.toml", toml)):
                    old = target / name
                    fresh = tmp / rel / name
                    fresh.parent.mkdir(parents=True, exist_ok=True)
                    fresh.write_text(content, encoding="utf-8")
                    if not old.is_file():
                        raise ValueError(
                            f"drift: {old} does not exist; run serve-spec first"
                        )
                    if old.read_text(encoding="utf-8") != fresh.read_text(encoding="utf-8"):
                        raise ValueError(
                            f"drift: {old} differs from a fresh render; "
                            f"run `awrtifact serve-spec {spec_path.name}` from "
                            f"{spec_path.parent}"
                        )
        return [t for t, _, _ in rendered]
    for target, js, toml in rendered:
        target.mkdir(parents=True, exist_ok=True)
        (target / "index.js").write_text(js, encoding="utf-8")
        (target / "wrangler.toml").write_text(toml, encoding="utf-8")
    return [t for t, _, _ in rendered]
